---
title: "Almond Model Yield Profit"
author: "Clarissa Boyajian, Desik Somasundaram, and Joe DeCesaro"
date: "4/11/2022"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(patchwork)
library(DT)
library(ggpubr)

source("function/yield_model.R")
source("function/yield_profit.R")
```

### Read in data

```{r}
climdf<- read.table("data/clim.txt", sep = "",
                    na.strings ="", stringsAsFactors= F)
```


### Computed Yield Anomaly

```{r, warning=FALSE}
climdf_summary <- climdf %>% 
  filter(year != 1988) %>% 
  group_by(year) %>% 
  summarise(t_min = mean(tmin_c),
            t_max = mean(tmax_c),
            precip_mean = sum(precip),
            yield_anom = yield_model(climdf,
                                     yearforyield = year,
                                     crop = "almond")
  )
```



### Explore Yield Data

```{r, warning=FALSE}
climdf_summary
```
### Test Yield Profit

```{r}
#Testing error messages
#yld_profdf <- yield_profit(yield_df=climdf_summary, price_per_ton=10, opcost_per_acre=500)
#yld_profdf <- yield_profit(yield_df=climdf_summary, price_per_ton=-10, opcost_per_acre=500)
#yld_profdf <- yield_profit(yield_df=climdf_summary, price_per_ton=10, opcost_per_acre=-500)
#yld_profdf <- yield_profit(yield_df=climdf, price_per_ton=10, opcost_per_acre=500)
```
### Generate Parameters for Informal Sensitivity Analysis

```{r}
deviation = 0.50
basealmondprice = 4000
price_per_ton = runif(min=basealmondprice-deviation*basealmondprice, 
                max = basealmondprice+deviation*basealmondprice, n=20)
```

```{r}
deviation = 0.50
baseopcost = 3900
opcost_per_acre = runif(min=basealmondprice-deviation*basealmondprice, 
                max = basealmondprice+deviation*basealmondprice, n=20)
```

```{r}
params_variability <- cbind.data.frame(price_per_ton,opcost_per_acre)
```


### Generate results using parameters generated

```{r}
results <- params_variability %>% 
            pmap(yield_profit,yield_df=climdf_summary)
```


### Visualize parameters from sensitivity analysis

```{r}
# now we can extract results from the list as above
mean_profit_anom = map_df(results,`[`, c("mean")) 
# and we can add the parameter values for each run
mean_profit_anom = cbind.data.frame(mean_profit_anom, params_variability)

# plot - pick on of the 2 parameter as a color

p1 = ggplot(mean_profit_anom, aes(price_per_ton, mean, col=opcost_per_acre))+
  geom_point(cex=2)+
  labs(y="Mean Profit Anomaly $/Acre", x="Price per Ton($)",
       col="Operating Cost $/Acre") +
  scale_color_viridis_c()
p2 = ggplot(mean_profit_anom, aes(opcost_per_acre, mean, col=price_per_ton))+
  geom_point(cex=2)+
  labs(y="Mean Profit Anomaly $/Acre", x="Operating Cost $/Acre",
       col="Price per Ton($)")+
  scale_color_viridis_c()

combined_plot <- ggarrange(p1,p2) 
combined_plot <- 
  annotate_figure(combined_plot, 
                  top = text_grob("Informal Sensitivity Analysis of Price and Operating Cost for Almond Profit Anomaly"))
combined_plot
```


```{r, eval=FALSE}
ggsave("figs/sensitivity_almond_profit_anom.jpg",combined_plot, width = 10, height = 7)
```



