---
title: "Model Use and Explanation"
author: "Clarissa, Desik, and Joe"
date: "4/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(patchwork)

source("function/yield_model.R")
```


```{r}
climdf<- read.table("data/clim.txt", sep = "",
                    na.strings ="", stringsAsFactors= F)
```



```{r, warning=FALSE}
climdf_summary <- climdf %>% 
  filter(year != 1988) %>% 
  group_by(year) %>% 
  summarise(t_min = mean(tmin_c),
            t_max = mean(tmax_c),
            precip_mean = sum(precip),
            yield_anom = yield_model(climdf,
                                     yearforyield = year,
                                     crop = "almond")
  )

climdf_temp <- climdf %>% 
  filter(year != 1988, 
         month == 2) %>%
  group_by(year, month) %>% 
  summarise(t_min = mean(tmin_c),
            t_max = mean(tmax_c))

climdf_precip <- climdf %>% 
  filter(year != 1988, 
         month == 1) %>%
  group_by(year, month) %>% 
  summarise(precip_mean = sum(precip))
```

```{r}
plot_yield <- ggplot(climdf_summary) +
  geom_line(aes(x = year,
                y = yield_anom))
plot_precip <- ggplot(climdf_precip) +
  geom_line(aes(x = year,
                y = precip_mean),
            col = "blue")
plot_temp <- ggplot(climdf_temp) +
  geom_line(aes(x = year,
                y = t_min),
            col = "red")

plot_yield / plot_precip / plot_temp
```



